### ISSUE TITLE
Не работает после обновления Padavan

### ISSUE THREAD

**Issue by olegkron** [blackcofee/rublock-vpn#1]
Вначале хотел бы поблагодарить @blackcofee за популяризацию данного способа обхода блокировок, без видео на ютубе я, да и думаю многие, об этом не узнали. Больше полугода на разных роутерах все работало без проблем.

Роутер Redmi AC2100, прошивка Padavan 3.4.3.9Z-102_15z5r2l
Работало исправно, но теперь при попытке доступа на какой-либо сайт из РКН-реестра просто виснет браузер до connection timeout'a. Провайдерскую заглушку уже не показывает, но и сайт не открывает. ВПН работает исправно, роутер также к нему исправно подключается. DNS проставлены как в инструкции, все скрипты и файлы также проверил, все ровно по инструкции. 
Хотел бы узнать, на что ,в логах ниже, следует обратить внимание, в чём может быть проблема.
Большое спасибо! 

Логи:
openvpn-cli[459]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1601'
openvpn-cli[459]: WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
kernel: UBIFS: recovery completed
kernel: UBIFS: mounted UBI device 0, volume 0, name "user"
kernel: UBIFS: file system size:   95232000 bytes (93000 KiB, 90 MiB, 750 LEBs)
kernel: UBIFS: journal size:       4825088 bytes (4712 KiB, 4 MiB, 38 LEBs)
kernel: UBIFS: media format:       w4/r0 (latest is w4/r0)
kernel: UBIFS: default compressor: lzo
kernel: UBIFS: reserved for root:  4498042 bytes (4392 KiB)
opt-mount.sh: started [/dev/ubi0 /mnt]
opt-mount.sh: call /opt/etc/init.d
olegkron: Started dnscrypt-proxy from .
dnscrypt-proxy[498]: dnscrypt-proxy 2.0.44
dnscrypt-proxy[498]: Network connectivity detected
dnscrypt-proxy[498]: Now listening to 127.0.0.1:65053 [UDP]
dnscrypt-proxy[498]: Now listening to 127.0.0.1:65053 [TCP]
dnscrypt-proxy[498]: Source [public-resolvers] loaded
dnscrypt-proxy[498]: Source [relays] loaded
dnscrypt-proxy[498]: Firefox workaround initialized
openvpn-cli[459]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
vpnc-script: tun0 up
dnscrypt-proxy[498]: [cloudflare] OK (DoH) - rtt: 10ms
dnscrypt-proxy[498]: [google] OK (DoH) - rtt: 22ms
dnscrypt-proxy[498]: Sorted latencies:
dnscrypt-proxy[498]: -    10ms cloudflare
dnscrypt-proxy[498]: -    22ms google
dnscrypt-proxy[498]: Server with the lowest initial latency: cloudflare (rtt: 10ms)
dnscrypt-proxy[498]: dnscrypt-proxy is ready - live servers: 2
NTP Client: Synchronizing time to pool.ntp.org.
watchdog: dnsmasq is missing, start again!
dnsmasq[988]: started, version 2.8x cachesize 1024
dnsmasq[988]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-UBus no-i18n no-regex no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify no-dumpfile
dnsmasq[988]: warning: ignoring resolv-file flag because no-resolv is set
dnsmasq-dhcp[988]: DHCP, IP range 192.168.31.100 -- 192.168.31.244, lease time 1d
dnsmasq-dhcp[988]: DHCP, sockets bound exclusively to interface br0
dnsmasq[988]: using nameserver 127.0.0.1#65053
dnsmasq[988]: read /etc/hosts - 3 addresses
dnsmasq[988]: read /etc/storage/dnsmasq/hosts - 0 addresses
dnsmasq-dhcp[988]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
dnsmasq[988]: using nameserver 127.0.0.1#65053
NTP Client: Synchronizing time to time.nist.gov.
NTP Client: System time changed, offset: 6.267581s
vpnc-script: tun0 down
openvpn-cli[459]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
openvpn-cli[459]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1601'
openvpn-cli[459]: WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
openvpn-cli[459]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
vpnc-script: tun0 up

*спустя некоторое время продолжает раз за разом выводить следующее*

vpnc-script: tun0 down
openvpn-cli[459]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
openvpn-cli[459]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1601'
openvpn-cli[459]: WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
openvpn-cli[459]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
vpnc-script: tun0 up
vpnc-script: tun0 down
openvpn-cli[459]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
openvpn-cli[459]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1601'
openvpn-cli[459]: WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
openvpn-cli[459]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
vpnc-script: tun0 up

**Comment by blackcofee** [comment]
А как связанна данная инструкция с настройкой openvpn клиента на конкретном ротере? В логе все написано, воспользуйтесь googlr переводчиком, либо обратитесь в тему роутера на 4pda.

**Comment by olegkron** [comment]
Здесь совсем не про роутер, и не про настройку OpenVpn, а про конкретную настройку обхода блокировок через dnsmasq и т.д. Для этого специально указал, что все исправно работало, вплоть до обновления.
Но даже после выполнения всех инструкций результата нет, поэтому и написал сюда, т.к. по логам скорее всего видно где может быть проблема.

**Comment by blackcofee** [comment]
Хм, на каком языке будет понятнее? Я же написал, проблема в настройке openvpn клиента и это написано в логах . Вместо того чтобы гадать, наверное нужно научиться читать?
